baseURL = "https://blog.secunda.casa"
languageCode = "en"
title = "Nirn's blog"
theme = "r1sp3r1d0n3"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false

[params]
  github = "Lilithbtw"
